# Deploy Django app to Azure Web App - myWebAppUlsterScalable01

name: Build and Deploy Django App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: environment_production  # 👈 THIS LINE IS REQUIRED (Environment name on Github)


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies for pyodbc
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev gcc g++

      - name: Create and activate virtual environment, install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django migrations and collectstatic
        env:
          DEBUG: false
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
        run: |
          source venv/bin/activate
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput

      - name: Zip the application for deployment
        run: |
          zip -r release.zip . -x "venv/*" ".git/*"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: django-app
          path: release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myWebAppUlsterScalable01'  # Update to your exact Azure Web App name
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E852983D5AD745A4937CCDD5492304B7 }}
